export const MockDataReviews = [
  {
    name: "Osama Salem",
    isVerified: true,
    size: 1,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 2,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 3,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 4,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 5,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 6,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 7,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 8,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 9,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 10,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 11,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 1,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 12,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 13,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 14,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 15,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 16,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 17,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 18,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 19,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 20,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 21,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 22,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 23,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 24,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
  {
    name: "Osama Salem",
    isVerified: true,
    size: 25,
    width: "Average",
    purchasedSize: 9,
    fit: "Just Right",
    activity: "Walking, Running, Errands",
    stars: 5,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 3, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 26,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Ahmed Saeed",
    isVerified: true,
    size: 27,
    width: "Average",
    purchasedSize: 8,
    fit: "Just Right",
    activity: "Walking, Running",
    stars: 4,
    header: "Very Comfortable.",
    msg: "Very Comfortable",
    date: "December 1, 2023",
  },
  {
    name: "Karim Shalapy",
    isVerified: false,
    size: 28,
    width: "wide",
    purchasedSize: 10,
    fit: "Runs Big",
    activity: "Traveling",
    stars: 2,
    header: "Very Comfortable.",
    msg: "Very Large",
    date: "December 2, 2023",
  },
];

export const MOCKDATADETAILS = {
  title: "details",
  description: `Our breathable, silky-smooth sneaker made with responsibly sourced eucalyptus tree fiber treads lightly in everything you do.`,

  paragraphs: [
    { title: `Best For:`, content: ` Walking, warmer weather, everyday wear` },
    {
      title: `Thermoregulating Material:`,
      content: ` Lightweight, breathable eucalyptus fiber provides next-level comfort`,
    },
    {
      title: `Versatile Design:`,
      content: ` Wear-with-everything classic style, great for travel`,
    },
    {
      title: `Where It’s Made:`,
      content: ` Vietnam. Learn more about our operations`,
    },
  ],
};
export const MOCKDATASUSTAINABILITY = {
  title: "sustainability",
  descriptions: [
    `Our Tree Runner has a carbon footprint of 4.99 kg CO2e. Learn more about carbon footprint labeling and our commitments to reduce our impact.`,
    `As a carbon neutral business certified by Climate Neutral, we balance our emissions by funding high impact carbon projects.`,
  ],
  listHeader: `Sustainable Materials:`,
  ulListItems: [
    `FSC-certified TENCEL™ Lyocell (eucalyptus tree fiber) upper`,
    `SweetFoam® midsole made with sugarcane-based green EVA`,
    `Bio-based TPU eyelets`,
    `Shoe laces made from recycled plastic bottles`,
    `Castor bean oil-based insole foam`,
    `ZQ merino wool heel lining`,
    `Some models may include a wool-lined insole instead of the TENCEL™-lined insole featured in the image`,
  ],
};
export const MOCKDATACARE = {
  title: "care guide",
  olListItems: [
    `Remove the laces and insoles.`,
    ` Place shoes in a delicates bag (pro tip: a pillowcase works too).`,
    `Choose a gentle cycle with cold water & mild detergent.`,
    `Shake out any excess water & set aside to air dry.`,
    `Shoes will regain their original shape with one or two wears. `,
  ],
  footer: `Want the full refresh experience? Swap in some new laces and insoles.`,
};
export const MOCKDATASHIPPING = {
  title: "shipping & returns",
  paragraphs: [
    `Free shipping on orders over $75, and our 30 days, no questions asked return policy. Lightly worn shoes get donated to Soles4Souls. Visit our Returns Portal.`,

    `Final Sale items cannot be returned or exchanged. Final Sale items include: gift cards, insoles, sock bundles, TrinoXO Face Masks, and items tagged final sale on our website and in Allbirds retail stores.`,

    `Need it sooner? See if the style you want is available at a store near you.`,
  ],
};
