import localFont from "next/font/local";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

import "./globals.css";

const geographFont = localFont({
  src: [
    {
      path: "./../assets/fonts/geograph-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../assets/fonts/geograph-medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../assets/fonts/geograph-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../assets/fonts/geograph-regular-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./../assets/fonts/geograph-medium-italic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
});

export const metadata = {
  title: "Allbirds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geographFont.className}>
        <p className="notice">This project is still in progress</p>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
